export * from './pages/person/PersonPage.vue'
export * from './pages/person/PersonProfile.vue'
export * from './pages/person/Persons.vue'
export * from './components/person/PersonList.vue'
export * from './components/person/PersonList.vue'
